services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./uploaded_img:/var/www/html/uploaded_img
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: bookstore
      DB_PASSWORD: bookstore123
      DB_NAME: bookstore_db
    networks:
      - bookstore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: bookstore123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./shop_db:/docker-entrypoint-initdb.d/shop_db
    networks:
      - bookstore_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123
      PMA_USER: root
      PMA_PASSWORD: root123
      PMA_ARBITRARY: 1
    networks:
      - bookstore_network
    depends_on:
      db:
        condition: service_healthy

networks:
  bookstore_network:
    driver: bridge

volumes:
  mysql_data:
