apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-prod

bases:
  - ../../base

commonLabels:
  environment: production

resources:
  - hpa.yaml

configMapGenerator:
  - name: bookstore-config
    behavior: merge
    literals:
      - app_env=production
      - app_debug=false
      - db_host=mysql-prod 