apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
type: Opaque
data:
  # These are example values. In production, use proper secret management
  db_user: Ym9va3N0b3JlX3VzZXI=  # bookstore_user
  db_password: Ym9va3N0b3JlX3Bhc3N3b3Jk  # bookstore_password 