apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore-dev

bases:
  - ../../base

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yaml

configMapGenerator:
  - name: bookstore-config
    behavior: merge
    literals:
      - app_env=development
      - app_debug=true
      - db_host=mysql-dev 